### PR TITLE
Version control for Docker images

### PR DESCRIPTION
**Pull request by MaximeVdB**
This PR adds a paragraph on version control for Docker images.

@gjbex Is this also how you would do it? Any other recommendations?

### CODE REVIEW

**Comment by gjbex** [comment]
@MaximeVdB This will only work when the Dockerfile is under version control.  Obviously, that is best practice, but it isn't what our users are doing.  Hence I'd suggest adding a second approach, which is to at least use version numbers in tags, so no "latest" that overwrites previous versions.

It is also worth pointing out explicitly that Artefactory doesn't do version control, and that if you store multiple versions of an image, that just amounts to storing unrelated sequences of bits.  The only semantics is imposed by the tags.

**Comment by MaximeVdB** [comment]
Thanks @gjbex, I agree. What do you think of the current version?

**Review by gjbex — APPROVED** [review]
Seems clear, hopefully the message gets across.

**Comment by MaximeVdB** [comment]
Thanks!

**Pull request merged**
